name: Scheduled Task

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render App API
        # run: curl -X GET https://blog-application-server-peou.onrender.com/api/v1/blogPost
        run: curl -X GET https://dummy.com
